import Head from 'next/head';
import FamousPlaces from '../components/FamousPlaces';
import Header from '../components/Header';
import SearchBox from '../components/SearchBox';
import Title from '../components/Title';

export default function Home() {
  return (
    <div className="">
      <Head>
          {/* Title */}
          <title>Weather App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="home">
        <div className="container">
          <Header />
          <Title />
          <SearchBox />
          <FamousPlaces />
        </div>
      </div>
    </div>
  )
}
